### ISSUE TITLE
Getting extra space at last column

### ISSUE THREAD

**Issue by Miteshdv** [ceolter/ag-grid-react#11]
Hi,
 I am getting extra space at last columns, Attached snapshot
![react ag extra space](https://cloud.githubusercontent.com/assets/18166868/14141859/761995a8-f69f-11e5-88cf-ec7ff17821e5.JPG) please help

**Comment by ceolter** [comment]
fix your column widths to the width of the grid.

either work it out yourself, or call api.sizeColumnsToFit()

**Comment by Miteshdv** [comment]
Thanks it worked ! can we give percent width to columns

**Comment by rajgopalk** [comment]
hi,
i got the same problem. i have used "$scope.gridOptions.api.sizeColumnsToFit();", still i got the same empty column. Is there any other solution for that...

**Comment by ahmermalik** [comment]
yeah, you should be able to give columns a percent width, it needs to be specified in the state:

` columnDefs: [
                {headerName: "ID",
                 field: "id",
                 width: 75},
                {headerName: "Title", field: "title",width: 130},
]`

**Comment by ThunderBoltEngineer** [comment]
Is there anyway to get rid of the empty column in the end?  I want the last column to take up its place.
