### ISSUE TITLE
Is support for treedata included in this component?

### ISSUE THREAD

**Issue by crazyUI** [ceolter/ag-grid-react#12]
HI

Will adding a callback function 'getNodeChildDetails' work here ? 

Thank you

**Comment by ceolter** [comment]
yes tree data is supported. see the docs.
https://www.ag-grid.com/angular-grid-tree/index.php

**Comment by crazyUI** [comment]
Do we have to do any custom changes for react component or it should work as it is explained in the documentation...

**Comment by ceolter** [comment]
as explained in the documentation.

only react changes needed if you want to use react for the rendering.
