### ISSUE TITLE
Select box in cell renderer causes react error when values changed

### ISSUE THREAD

**Issue by marcuswhit** [ceolter/ag-grid-react#13]
Using React@0.14.7, with ag-grid@4.0.5 and ag-grid-react@4.0.0, I have a grid with the following columns:

```
{ field: 'include', headerName: 'Include', width: 60, cellRenderer: reactCellRendererFactory(this.renderCheck.bind(this)), pinned: 'left' },        
{ field: 'delivery', headerName: 'Delivery', width: 100, cellRenderer: reactCellRendererFactory(this.renderDelivery.bind(this)), pinned: 'left' }
```

The renderer functions look like:

```
renderDelivery({params}) {
    let setSelectionOptions = ['Physical', 'Cash'];

    return (
        <select value={params.value}
            onChange={e => this.deliveryChanged(params.data.id, e.target.value)}>
            {setSelectionOptions.map(o => <option key={o} value={o}>{o}</option>)}
        </select>
    );
}

deliveryChanged(id, delivery) {
    // dispatch redux action
    this.props.dispatch({ type: Actions.DELIVERY_CHANGED, payload: {id, delivery} });
}

renderCheck({params}) {
    return <input type="checkbox"
                  checked={params.value}
                  onChange={evt => this.onIncludeToggled(params.data.id, evt.target.checked)} />;
}

onIncludeToggled(id, isChecked) {
    this.props.dispatch({ type: Actions.INCLUDE_TOGGLED, payload: {id, isChecked} });
}
```

This renders correctly and values are correctly bound.  I can toggle the checkbox column values without issue and they're correctly bound and updated.  However, with the select box column, I can only update one or two rows before it throws the following React error when I try to update subsequent rows or scroll:

```
TypeError: Cannot read property 'mountComponent' of undefined
```

This usually corrupts the grid and the rows below disappear. The stack trace is below.  

![2016-04-14 12_01_07-developer tools - http___localhost_8001_](https://cloud.githubusercontent.com/assets/2963426/14514954/aead29a8-0238-11e6-8525-91576cbf391a.png)

**Comment by marcuswhit** [comment]
Hi, any thoughts on this?  We're evaluating the grid for our project, and this is the main showstopper at this stage.  Thanks.

**Comment by ceolter** [comment]
from my side, i do not know what is wrong. i have only read into react enough to provide the react component, i don't have any industry experience using it.

to get around it, would you consider not using react inside the renderer?

you could also try posting this on the forum - more people look at the forum and try to help than github, could get talking to other react users.

**Comment by seanlandsman** [comment]
Closing as this shouldnt be an issue anymore - please let us know if you still  have a problem with this
