### ISSUE TITLE
How to link selections, sorting with state?

### ISSUE THREAD

**Issue by light049** [ceolter/ag-grid-react#14]
Are there ways to link sortModel and check selections with state?
Coz after setState for other components, the selection and sorting status of ag-grid would not be rendered again...

Thanks~

**Comment by seanlandsman** [comment]
Hi

You can programatically force a sort by doing something like 

    gridOptions.api.setSortModel(gridOptions.api.getSortModel());

You could trigger this when the state changes in one of your components
