### ISSUE TITLE
Re-render of grid with grouped data does not render grouped headers correctly

### ISSUE THREAD

**Issue by aditigoel23** [ceolter/ag-grid-react#15]
I want the grid to render with grouped/non-grouped data on demand. 

If I render the grid with grouped data (tree data) on load it renders correctly. On subsequent updates to grouped data the grid re-renders correctly.
If I render the grid  with non-grouped data on load it renders correctly.

Now if new data is pushed from parent component which is in grouped format, the grid doesnt render grouped headers properly. 
I can see  getNodeChildDetails gets called and does the right thing but if I add a callback for groupRowInnerRenderer, it never gets called.

**Comment by seanlandsman** [comment]
Hi

This should work as expected now - if this is still an issue can you please let us know

thanks
