### ISSUE TITLE
What is minimum version of React used with ag-react-grid

### ISSUE THREAD

**Issue by mikeerickson** [ceolter/ag-grid-react#16]
I am using with React 0.13.1 (we cant upgrade to React 0.14 (or 15) yet.

I am having issues using ag-grid and am curious if it is related to our React version

I have created a sandbox test and all works fine (but that uses React 0.14)

```
Error: Invariant Violation: Constructor.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
```

**Comment by ceolter** [comment]
React component was written with most recent React lib at time if writing,
Jan 2016. I have not tested again St other versions. The grid only wraps
the itself using react, using very minimal react. Would be surprised if
that's an issue.

**Comment by mikeerickson** [comment]
Have you had any users report issues when using w/ ngReact.  Stumped on what could be causing the issue.  Thx for reply

**Comment by ceolter** [comment]
No.

Try using the plain javascript version, see of its the grid core or react
interfacing that is causing the issue.

**Comment by mikeerickson** [comment]
Funny, that is what I was thinking last night.  I will give it a whirl over the weekend

**Comment by mikeerickson** [comment]
@ceolter Just an FYI, I got everything working (within ngReact in Angular v1 app).  The biggest issue was the version of React we had.   I upgraded from 0.13.1 to 0.14.8 and all was good from that point.

Not saying specifically that ag-grid requires React 0.14.8, but it was the cure for my issues

**Comment by ceolter** [comment]
@mikeerickson thanks for info
