### ISSUE TITLE
React context not working (as the reactCellRendererFactory creates the React components outside of the main React tree)

### ISSUE THREAD

**Issue by gabrielenosso** [ceolter/ag-grid-react#17]
I am using a react library for drag and drop (which is 'react-dnd', the most famous one).
I am trying to have some table cells in which I can drop some components.

The problem is that using reactCellRendererFactory to create cellRenderers puts the resulting component instances outside of the main tree.

In that way, the React context is not passed to the children.
And that library, as many others, are based on that feature (as there is a strong relationship between the components and its container).

To explain it better, this is what I have in the React tree
![aggrid react context problem](https://cloud.githubusercontent.com/assets/4018887/14886930/b8461fa8-0d53-11e6-910d-ed461f461259.png)

Is there a way to solve that?

**Comment by ceolter** [comment]
i'm not aware of any way to solve this.

as you point out, React DnD has a dependency on your entire applicaiton using React. because ag-Grid doesn't use React, it's not possible (afaik) to use you DnD service
