### ISSUE TITLE
Cant able to create cell editor

### ISSUE THREAD

**Issue by jaya7660** [ceolter/ag-grid-react#19]
I am trying to implement custom editor component for react aggrid table. Can you please tell me how to implement custom table cell editor component using react-aggrid?

**Comment by ceolter** [comment]
You cannot use React inside the cellEditor, unless you bind into the React
rendering engine yourself.

Please use native DOM to build to cellEditor.

**Comment by seanlandsman** [comment]
Hi

Please refer to https://www.ag-grid.com/javascript-grid-cell-editor/?framework=react for information on using react components as cell editors
