### ISSUE TITLE
Tree node row selection is not working

### ISSUE THREAD

**Issue by jaya7660** [ceolter/ag-grid-react#21]
I am using tree node for splitting table rows. But after using tree node parent row is not selecting.
What can i do so that rows selection will work for parent row?

**Comment by bogdanandreica** [comment]
Use both onRowClicked and onRowSelected callbacks in your gridOptions object. In the onRowClicked callback call node.setSelected(true) for parent nodes. This will fire onRowSelected. Hope will help.

**Comment by seanlandsman** [comment]
I believe that this issue is now resolve. Please let us know if this is not the case

**Comment by d4e666** [comment]
I upgraded my grid to the latest version (10.1.0) and the issue remains. Can you tell me what options you set to solve this? 

![image](https://user-images.githubusercontent.com/7936919/26978123-8f595e4e-4d2a-11e7-8eef-1a79eea25f27.png)
