### ISSUE TITLE
Dragging grouped column into pinned breaks functionality

### ISSUE THREAD

**Issue by Siern** [ceolter/ag-grid-react#22]
When dragging a grouped column into a pinned section, it breaks when column group expansion is clicked.  The result is after expansion all columns except the left pinned columns are now missing!

steps to reproduce:
Sample column definition:

```
{
 {
  headerName: "leftPinned",
  pinned: "left",
 },
 {
  headerName: "middle1",
 },
 {
  headerName: "middle2",
 },
 {
  headerName: "rightPinned",
  pinned: "right",
 },
 {
  headerName: "Sports Results",
  children: [
    {headerName: "Sport", field: "sport"},
    {headerName: "Total", columnGroupShow: 'closed'},
    {headerName: "Gold", columnGroupShow: 'open'},
    {headerName: "Silver", columnGroupShow: 'open'},
    {headerName: "Bronze", columnGroupShow: 'open'}
    ]
 }
}
```

Drag the "sports Results" column to the "rightPinned" so it is in the pinned part, so that is now part of that pinned group.  
Then click the + to expand the header group.

My result in this example is only the "leftPinned" in now visible.
This does not occur if it is drug into the left pinned area.

**Comment by ceolter** [comment]
can you demonstrate this on the main demo?
https://www.ag-grid.com/example.php

easier than having to set up your example, thanks.

**Comment by Siern** [comment]
Yes.
but in the process I have found that the problem may be unrelated to the grouped column.
It simply appears that when there is not enough room to render the left pinned columns and the right pin columns, the grid decides to render the left and leave the rest of the grid space blank.

you can see that in your demo by pinning something to the left then add some right pins and reduce the browser size until they meet.

**Comment by ceolter** [comment]
hmmm, i'll think about it. not sure how to best fix.

**Comment by seanlandsman** [comment]
I believe that this issue is now resolve. Please let us know if this is not the case
