### ISSUE TITLE
table header is messed up

### ISSUE THREAD

**Issue by matrixl** [ceolter/ag-grid-react#25]
upgraded to version 5.0.0 (ag-grid version 5.0.1), the header is messed up.

![screenshot](https://cloud.githubusercontent.com/assets/806423/16713680/1567e140-46e2-11e6-9376-202690a530cc.png)

**Comment by ceolter** [comment]
Give more info. All the examples work for me in chrome. The main demo works in all browsers I test against.

**Comment by matrixl** [comment]
I found the problem. the header cell css "position" is "absolute", it works ok after i changed to "relative". not sure if this is caused by my global css style or a bug in the ag-grid. you may close the case if this is not an issue.

.ag-header-cell {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
    vertical-align: bottom;
    text-align: center;
    display: inline-block;
    height: 100%;
    **_position: absolute;_**
}

change to 

.ag-header-cell {
  ...
  **_position: relative;_**
}

**Comment by ceolter** [comment]
thanks for the update
