### ISSUE TITLE
React + redux

### ISSUE THREAD

**Issue by UweWindt** [ceolter/ag-grid-react#26]
i 'm using React+Redux + ag-grid.

Everything works fine, but:

When i have a rowselected and refresh the data (reloading from Server)  the selection got lost.
Is there an event where i can programatical set a selection (which i keep  in the redux-store), when the new rowData have loaded and processed?

Thx

**Comment by ceolter** [comment]
no.

but you can keep an copy of the selection yourself, and then set the selection again after the reload.
