### ISSUE TITLE
FloatingCellEditor similar to floatingCellRenderer

### ISSUE THREAD

**Issue by saivikas7875** [ceolter/ag-grid-react#28]
First, @ceolter: :+1: on the amazing ag-grid

I have a question regarding a scenario where I would like the column's floating row cell to be a cell editor along the lines of `floatingCellRenderer`? Something like `floatingCellEditor` would be awesome.

Alternate solutions I see is to define the `HTML` in the `floatingCellRenderer` to be an input.

**Comment by ceolter** [comment]
fair point. i've added this to the core grid project as it's not specific to react implementation.
https://github.com/ceolter/ag-grid/issues/1078

**Comment by saivikas7875** [comment]
Thanks. Appreciate it!
