### ISSUE TITLE
Ability to specify styling on the container element

### ISSUE THREAD

**Issue by jeffshaver** [ceolter/ag-grid-react#29]
In the `AgGridReact` component file, the render method always applies a 100% height to the, I would like to ability to specify styles for that container. The problem I am having right now is that the height setting is causing issues with flexbox. I want the height to be "auto" since I am already dealing with the height in other ways. 

It would be nice if height: 100% was the default but could be overwritten by a developer.

```javascript
render: function () {
  return React.DOM.div({
    style: {
      height: '100%',
      ...this.props.containerStyle
    }
  });
}
```

**Comment by ceolter** [comment]
i have changed to the following, will be in the next release:

```
    render: function() {
        return React.DOM.div({
            style: this.createStyleForDiv()
        });
    },

    createStyleForDiv: function() {
        var style: any = {height: '100%'};
        // allow user to override styles
        var containerStyle = this.props.containerStyle;
        if (containerStyle) {
            Object.keys(containerStyle).forEach( key => {
                var value = containerStyle[key];
                style[key] = value;
            });
        }
        return style;
    },
```

ps i have a lot on these days and am not familiar with props.containerStyle - can you advise if my code is correct?

**Comment by jeffshaver** [comment]
`containerStyle` was just a suggestion for a prop name (since style should probably apply to the table itself). My problem was that I was using flex on on a parent and the height on this container was causing some issues. So I needed to be able to override the height option. But the way you did it allows for other style changes as well. So i think this solves my issue and will help with the flexibility of the styles going forward. I appreciate your quick response to this issue!

**Comment by ceolter** [comment]
cool. welcome :)
