### ISSUE TITLE
UMD definition

### ISSUE THREAD

**Issue by esbenp** [ceolter/ag-grid-react#3]
Would it be possible to add UMD definition in the compiled source to make it usable with AMD modules?

**Comment by ceolter** [comment]
how do you do that? and what does it do?

On 16 February 2016 at 11:55, Esben Petersen <notifications@github.com>
wrote:

> Would it be possible to add UMD definition in the compiled source to make
> it usable with AMD modules?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/ag-grid-react/issues/3>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by seanlandsman** [comment]
Closing as now old and stale - if still relevant feel free to raise a new one

**Comment by petyosi** [comment]
We are going to include an UMD bundle in the next release: https://github.com/ag-grid/ag-grid-react/commit/30ae00240aed5e5265aa877e8ecb9fa34dce0c94
