### ISSUE TITLE
Issue when server side testing

### ISSUE THREAD

**Issue by dlvx** [ceolter/ag-grid-react#30]
When testing a React component with enzyme shallow, using shallow rendering, and if this specific component or any of it's children use ag-grid-react I get the HTMLElement is not defined error, issued here:

https://github.com/ceolter/ag-grid-react/issues/24

My issue is kind of similar, but I'm not getting it when running webpack, but when running tests, even tho, adding this line to gridCore.js and agCheckbox.js will fix the error:

var HTMLElement = typeof HTMLElement === 'undefined' ? function(){} : HTMLElement;

Of course HTMLElement won't exist when server side JS is excecuting this component, but the fix above is not a permanent one, specially when node_modules are beign ignored.

Is there a way ag-grid-react could include a line like the above so shallow tests or any other server side test that fails at this point could work? 

Thanks

**Comment by shabareesh** [comment]
HI, 
I am also facing "ReferenceError: HTMLElement is not defined" issue while testing the component, as previous comment when i added HTMLElement check it fixes the issue.

Are you going to fix this issue or is there any work around ?

Thanks

**Comment by ceolter** [comment]
ag-Grid has a dependency on the DOM - so if you are doing server side testing, you will need to mock the DOM. if the above fix works for you, i'd rather you put it into your code rather than have ag-Grid start to mock the DOM out.
