### ISSUE TITLE
Stop editing when clicked outside the component

### ISSUE THREAD

**Issue by mieryn** [ceolter/ag-grid-react#31]
It would be great if stopEditing() would be called when clicking outside the ag-grid React Component. There is a mixin (react-onclickoutside) and HOC (react-click-outside) for this if you don't want to implement this yourselves. At least the mixin is really easy to add to agGridReact.

**Comment by ceolter** [comment]
this was the way the grid worked initially, in that the editor stopped if the focus was lost on the cell - so any click outside of the cell, regardless on in the grid or outside the grid, would stop the editing.

this did not work as people were using third party libraries (eg date pickers) that were rooted outside of the grid for editing, so it didnt work. hence the change to it stops editing when another cell starts editing.

if you want to stop editing, there is an api method stopEditing() that you can call when focus goes outside the grid.

**Comment by grovesNL** [comment]
@ceolter: Could you recommend a method to listen for this blur event while using the default cell renderer? I'm attempting to do what's described above.

**Comment by instantaphex** [comment]
I'm having this problem as well.  It really makes users frustrated when they go to edit a cell, then they click the save button and the cell does not stop editing and their changes are not saved.  Of course I can put a stopEditing() call in my save method, but that only works if my save method is in the same scope as my gridApi, which isn't always the case.  There must be some way around this, I just can't find it.

**Comment by sherif2016** [comment]
@instantaphex, Exactly I'm at the same requirement that I want the edited cell value to be stored when I click "SAVE" but still the cell is focused so I'm not able to get the edited value. Please post if someone has the solution for this problem.

**Comment by nishantgirbar** [comment]
@sherif2016 @instantaphex : I have same issue, did you get any chance to fix this.

**Comment by EoinGriffin-AI** [comment]
This really ought to be a grid configuration property (or column definition property).
Dev team, is this on your roadmap? If not, would you be willing to re-add this feature?

**Comment by erfangc** [comment]
@ceolter what is the correct way to determine when the grid is out of focus
per your comment:
"if you want to stop editing, there is an api method stopEditing() that you can call when focus goes outside the grid."

**Comment by jdewell** [comment]
Did anyone find a solution to this?

**Comment by DevBono** [comment]
I think I found some property, **stopEditingWhenGridLosesFocus**

I'm using Angular, but I had same problem with you guys. 

But after using that option on gridOptions: { stopEditingWhenGridLosesFocus: true } 

the problem was solved, in my case.
(Edit cell, and just click outside or empty row in grid, the onCellValueChanged event was invoked)

p.s. I'm using ag-grid 16.0.0 / ag-grid-angular 16.0.0

**Comment by sivaramalingam** [comment]
I used **stopEditingWhenGridLosesFocus** property, it was worked only in IE but not in chrome for my case. I applied drag and drop, single click edit on the grid. Whenever i focused the cell in Chrome, having the below issue, and unable to enter the value onto this. 

 **Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?**

p.s I used angular 2, ag-grid: 12

**Comment by iosifpetre18** [comment]
So there is a good solution for this?
I set stopEditingWhenGridLosesFocus: true but I get the error:
Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

**Comment by Sprokopyak** [comment]
> So there is a good solution for this?
> I set stopEditingWhenGridLosesFocus: true but I get the error:
> Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

I found that this issue happened because my logic built so when I did editing at the input field, it called method `param.node.serDataValue`, and this error was because of it, I changed a bit my logic and don't use this method now and everything work fine

**Comment by mugathi** [comment]
I used stopEditingWhenGridLosesFocus: true in gridOptions object. It worked for me 
Thank you guys for helping me out

**Comment by nnguyenleap** [comment]
I submitted a pull request regarding this, by wrapping `removeAllChildren` function in a try-catch block.

This doesn't cause any harm to the logic, yet prevent the `removeChild` error from breaking the whole grid. Maybe a better solution should be considered to solve the racing of removing `lastChild node`.

[https://github.com/ag-grid/ag-grid/pull/2892](https://github.com/ag-grid/ag-grid/pull/2892)

**Comment by enchanter5525** [comment]
When I implement stopeditingwhengridlosesfocus my date picker is not working. Did anyone get solution for this?

**Comment by stepet80** [comment]
I have the same problem. I have auto numeric editors and date time editors and it doesn't work well with this option giving an error.

**Comment by jfstephe** [comment]
Don't use stopEditingWhenGridLosesFocus with [custom popups](https://www.ag-grid.com/javascript-grid-cell-editing/#losingFocusStopsEditing). In you're 'save' button you need to tell the grid to stop editing. e.g.

gridOptions.api.stopEditing();
