### ISSUE TITLE
filterModel appears to be reset on render()

### ISSUE THREAD

**Issue by sjmatta** [ceolter/ag-grid-react#33]
Every time `render()` is called, it appears `filterModel` gets reset. The same thing doesn't happen to `sortModel`.

Text appears fine in the filter box, but filterModel doesn't reflect what's actually typed in the box.
```
var datasource = {
    getRows: function(params) {
        console.log(params.filterModel);
        console.log(params.sortModel);
        params.successCallback(winners.slice(params.startRow, params.endRow));
    }
};
```

Let me know if I can provide additional detail.

See https://ide.c9.io/shaydin/ag-grid-react-test for a whittled-down example. I couldn't get it working in jsFiddle - sorry about that.

**Comment by ceolter** [comment]
set newRowsAction to 'keep'
https://www.ag-grid.com/javascript-grid-filtering/index.php

**Comment by sjmatta** [comment]
Perfect. Thanks! :+1:
