### ISSUE TITLE
reactCellRendererFactory leads to severely degraded performance for large tables

### ISSUE THREAD

**Issue by dhassouni** [ceolter/ag-grid-react#34]
It seems as though implementing a simple react cellRenderer via the component method can be coded elegantly and efficiently. I have a table with ~35 columns, most of which have this simple renderer that is really just modifying the format.  With a small number of rows (<30), performance is fine. However, if I pull in a relatively modest number of rows (~300), performance takes a hit to the point that the scroll is more or less not useable. 

I ultimately changed my cellRenderer to a functional renderer returning an HTML string since I was just doing formatting, and the performance is significantly improved. I'm not well-versed enough in the inner workings of React to suggest an appropriate improvement for the reactCellRendererFactory, but it pretty clear that this is causing the problem. It would be great to have this working as well as agGrid works in almost every other scenario (beautifully!). I have tried this same react component as a cell renderer in a competing, but less fully-featured data grid (ZippyUI's react-datagrid), and it does not suffer from the same issue, so I'm not inclined to think this has anything to do with just having too many react elements in the data grid.

**Comment by ceolter** [comment]
using React dev / debug mode slows things down a lot. can you verify you have React debug turned OFF and test again?

**Comment by dhassouni** [comment]
Thanks for the quick response. That's a good catch. I threw the following into my config file and the speed definitely improved.
```
    new webpack.DefinePlugin({
        'process.env': {
            NODE_ENV: JSON.stringify('production')
        }
    })
```
The grid's scroll went from being essentially unusable in dev/debug mode to useable in production mode -- perhaps to the point where you may no longer consider this a bug. However, it is still not nearly as performant as the non-React version of the renderer I made. In our use case, being able to scroll quickly is quite important, so I'll stick with the vanilla HTML string renderer for now. There will be other types of renderers where this won't be ideal. In any event, I'll leave this to you to consider whether there is anything else you wan to address here. Thanks again.

**Comment by ceolter** [comment]
cool. will then close. however i'm wondering what can be done to make it faster. see this PR here:
https://github.com/ceolter/ag-grid-react/pull/32

not yet merged, but i'm wondering, if you did use it, and provided a parent component, would it make it faster. i'm wondering if there is overhead with React having lots of isolated rendered parts (which is happening currently for you, the different React cells are not aware of each other).

**Comment by dhassouni** [comment]
This seems to make some sense because I used the same renderer in ZippyUI's react-datagird as I tried to use here in ag-Grid. ZippyUI is coded in react native, so the key difference would be that it smoothly fits into the React architecture and perhaps there is value in the chain of react components as opposed to ReactDOM.render()ing so many individual components.

**Comment by ceolter** [comment]
yup will merge that PR soon. i'll close this issue as that PR i believe is the solution. thank you for the feedback re ZippyUI, gives me hope speed on React with ag-Grid is around the corner!!!

**Comment by ceolter** [comment]
i've updated the React example to now use this.
