### ISSUE TITLE
ag-Grid React Column Menu - Main Panel sub menu location is way off for columns to right of grid

### ISSUE THREAD

**Issue by dhassouni** [ceolter/ag-grid-react#35]
I am noticing that when I try using the pinning submenu on a column that is on the right side of my grid, I would expect the submenu to show up on the left. This happens on the basic Column Menu examples found here: https://ag-grid.com/javascript-grid-column-menu/index.php.

However, I don't even need a code snippet to showcase the problem because the React example (https://ag-grid.com/best-react-data-grid/index.php) suffers from the same problem. Try to pin the Mobile or Proficiency columns, and you can see that the submenu opens way off the page. Seems as though the logic for where to place the submenu needs to be updated - and I've only noticed this issue on React examples.
![screen shot 2016-09-07 at 6 33 32 pm](https://cloud.githubusercontent.com/assets/3877429/18333152/c245f8aa-7529-11e6-912f-3bcccb7904e8.png)

**Comment by ceolter** [comment]
this was an issue in the core ag-Grid, not the ag-grid-react bit.

fixed now. will be included in next release. thanks for raising.

**Comment by ceolter** [comment]
btw, it happened when the grid was not aligned to the left of the page - the menu popup was not taking into consideration that the grid top-left was NOT at pixel (0,0) when working out the new x position

**Comment by dhassouni** [comment]
Thanks for the quick fix. I guess the react portion was just a red herring.

**Comment by ceolter** [comment]
yup - it's the only example in the docs embedded into the page (not an iframe), so was the only one that suffered.

**Comment by dhassouni** [comment]
Hi @ceolter, I noticed that there was a release today, but this doesn't seem to be fixed in the example. Just curious if I am missing something, or if maybe that fix was on a branch that wasn't included in this release.

(I am, however, noticing other great react work being done with respect to the filters and cell renderers, thanks!)

**Comment by dhassouni** [comment]
So, it does seem that the issue I was noticing in my application is fixed. As noted, the React example on the ag-grid page (https://ag-grid.com/best-react-data-grid/index.php) is not working quite right and I'm not clear why. In my own application, the submenu goes off to the left when running into the right border, as I might hope for.

**Comment by ceolter** [comment]
hi @dhassouni , sorry for the delay, we are discovering sponsoring conferences and it's taking it's told on my time. can you advise - is this still an issue?

**Comment by dhassouni** [comment]
Hi @ceolter. No problem, thanks for getting to this. Yeah, like I had said, this is working great now in my own application. 

It is not, however, fixed in the React example in the ag-grid documentation. So, it is fine for my needs, but I'm not clear why that isn't translating to the example (of which I posted a picture above). It looks like the git repo for the ag-grid-react-example was using the updated versions of ag-grid where you supposedly fixed the issue?

**Comment by ceolter** [comment]
ah right - the example online in our webpage isn't the latest. we don't update it with every release. that's the reason.

**Comment by dhassouni** [comment]
Well fee free to close this case then, because I can confirm the fix works in the latest release. Thanks!
