### ISSUE TITLE
Multiple formats for floating rows/ headerCellRenderer

### ISSUE THREAD

**Issue by saivikas7875** [ceolter/ag-grid-react#37]
Hi @ceolter. Thanks for the increased support for the react in v6.0.1.

I have a scenario using the `ag-grid-react` component that requires different formats for the `floatingRows`. 

Approach 1: Provide custom `floatingRowCellRenderer` to each frozen row

Approach 2: An alternate approach  was to use `headerCellTemplate` to modify the header cell to behave as two rows of frozen data, the first being the header name and second one being the pseudo frozen row. But this needed to be a react component via the new RendererFramework method

For both the approaches, I face a small blocker
* Allow custom formatting for each row of floating row data via floatingCellRenderer (this might limit the scenario where cell needs to be an editor)
* Allow `headerCellTemplate` to be a react component via `headerCellRendererFramework`

Do you think of an alternate (React)way to do it or if either of these solutions are possible in anyway?

**Comment by saivikas7875** [comment]
I was able to combine couple of things to meet this requirement,

I used `floatingCellRendererFramework` to render a single cell in the floating row for a column and then modified the height of the `floatingRow` using the `getRowHeight` call back to change the height and then used the react component I was passing to `floatingCellRendererFramework` to behave as two rows. 

Closing this issue. Feel free to reopen if the need to update the two points I mentioned arises.

**Comment by ceolter** [comment]
re headerCellTemplate - having framework components up there is a bit of work. it's on our 'to do' list - however i need to refactor how the headers work first to allow it - so it's not a simple change.

the solution you propose does work.

having a different component per row never occurred to me. your the first to ask for it. given it's a rare requirement (ie just one person) i'm slow to include support for it in the grid.

what i would do personally is have one component. that would be a wrapper component that you provide that would decide what to render based on some property. you could have something set on your data so it knows what row it is.

**Comment by ceolter** [comment]
thank you for taking the time to come back and close the issue btw, that helps a lot.
