### ISSUE TITLE
Looking for headerCellRendererFramework

### ISSUE THREAD

**Issue by bright-sea** [ceolter/ag-grid-react#38]
cellRendererFramework is quite useful for using react component to renderer cell. Can we have this feature for headerCellRenderer as well, ie. add a headerCellendererFramework so that we can use react component to renderer header cell.

**Comment by saivikas7875** [comment]
Need some love for this @ceolter :)

**Comment by ceolter** [comment]
yes that's on our plan. the issue is that i need to refactor how the header rendering is done. but we want to include this and allow your framework components in the header.

**Comment by bright-sea** [comment]
@ceolter  Would you mind to share any update for adding this feature? Is it still postponed to unknown future or it maybe in near future?

Thanks

**Comment by jameswyse** [comment]
Looks like this will be possible in the version 8.x, which i think is due for release this week :)

**Comment by bright-sea** [comment]
@jameswyse It's so great to hear this. Thanks!

**Comment by bright-sea** [comment]
@jameswyse I just checked varsion 8.2 and still not found this. 

@ceolter Any update?

Thanks

**Comment by jameswyse** [comment]
https://www.ag-grid.com/javascript-grid-header-rendering/?framework=react#gsc.tab=0

Check `headerComponentFramework` :)

**Comment by bright-sea** [comment]
@jameswyse  Thanks a lot!  I will give it a try.

**Comment by seanlandsman** [comment]
I believe that this issue is now resolved. Please let us know if this is not the case
