### ISSUE TITLE
StartEditingCell isn´t accesible in React ?

### ISSUE THREAD

**Issue by Maikel-mg** [ceolter/ag-grid-react#41]
I am trying to replicate the example "Cell Editing" in React, but when I try to call to the function api.startEditingCell, It throws a Type Error  **api.startEditingCell is not a function**. The function stopEditing works fine.

¿How can I put in editing mode a cell in React?

**Comment by buddyp450** [comment]
Check this out and see if it helps at all, I was able to work out my issues with the React version once I had this guiding example:

https://github.com/ceolter/ag-grid-react-example/blob/master/src-standard/NameCellEditor.jsx

You don't actually need to trigger the cell editing from within the component, as long as it's editable from the grid's perspective (and `editable :true` in your column definitions).

Focus is different though and you'll need to use the afterGuiAttached() method in the example provided.

**Comment by ceolter** [comment]
should be working fine - assuming you are using the latest ag-Grid, then all the api methods are present, React has access to all methods, properties etc. if one api method works, but not the other, then i'm thinking a version mismatch???

**Comment by seanlandsman** [comment]
I believe that this issue is now resolve. Please let us know if this is not the case
