### ISSUE TITLE
Unable to refresh floating rows

### ISSUE THREAD

**Issue by psumstr** [ceolter/ag-grid-react#43]
I've created a cellRenderer component that's working properly for non floating rows. I can call grid.api.refreshCells(nodes, colId) and the refresh method of my cellRenderer gets called. Unfortunately, I haven't been able to do the same for the floating rows. Even if I pass a floating row node to refreshCells, the refresh method does not get called.

Am I missing something?

**Comment by ceolter** [comment]
refreshCells() doesn't update the floating rows, only the main core rows.

to refresh the floating rows, call api.refreshView(), or set the data again for the floating rows ie api.setFloatingTopRowData() or api.setFloatingBottomRowData()
