### ISSUE TITLE
Global quickFilterText does not work with cellRendererFramework

### ISSUE THREAD

**Issue by eberhara** [ceolter/ag-grid-react#44]
I am using `<AgGridReact />` to render a couple of React Components on its cells.
However, it seems that `quickFilterText` does not work when you render a react component inside of the grid.

Here is my ag-grid component and column defs:
```
import MyComponent from '../components';
const columnDefs = {
    ...
    cellRendererFramework: MyComponent,
    keyCreator: ({ value }) => (
        value.firstName
    ),
};

<AgGridReact
    ...
    columnDefs={columnsDef}
    quickFilterText={this.state.quickFilterText}
/>
```

My cell value (value passed to the react component) looks like this: `const value = {firstName: 'First', lastName: 'Last', picture: 'picture.png'};`.

The grid is considering the value of the cell like `[object Object]`. I could find this out due to 2 facts:
- grid returns all rows when I type `[object object]` into quickFilterText.
- when I `this.api.exportDataAsCsv()`, it returns me a CSV with `[object Object]` in all cells containing a react component.

Does anyone know if I should use any param (other than `keyCreator`) to fix those 2 scenarios?

**Comment by ceolter** [comment]
this has nothing to do with React, but how you are using embedded objects in your data.

the grid calls toString() on the object to get the text to use in the quick filter.

so if the values is a string or a number, this all works well. if it's an object, as you are experiencing, it doesn't work well!

the only workaround is to provide toString() as a method on your objects, which will return a proper string representation of the data.

if you want to see what's happening, debug through the grid code, you will see the quick filter getting set on this method ```aggregateRowForQuickFilter```
