### ISSUE TITLE
Adding/deleting Items from tree

### ISSUE THREAD

**Issue by Miteshdv** [ceolter/ag-grid-react#45]
Hi ,
 I am using AG grid to display Tree data ,using AG grid's Browse file example.

But when I am trying to add or delete  items from tree I get following warning and operation doesn't work.
"**ag-Grid: adding and removing rows is not supported when using nodeChildDetailsFunc, ie it is not supported if providing groups**"

Please help !

Thanks

**Comment by ceolter** [comment]
as the message says, adding and removing is not supported when you are using tree view.

the only option you have is set all the data back in again from scratch.

**Comment by dush-man** [comment]
Is there any update on this issue? Not user friendly when dealing with large data sets.

**Comment by rjraj12** [comment]
hi @ceolter  , any updates on this?
