### ISSUE TITLE
A wrong value for rowHeight crashes the browser

### ISSUE THREAD

**Issue by jdelafon** [ceolter/ag-grid-react#48]
I made the mistake of giving the rowHeight property in pixels:

    <AgGridReact
          rowData={data}
          columnDefs={columns}
          rowHeight="25px"
    ></AgGridReact>

Instead of getting an error, Chrome starts using 100% CPU and I need to force kill it.

"ag-grid": "^6.2.1",
"ag-grid-react": "^6.2.0",
Chrome 54.0

**Comment by seanlandsman** [comment]
Thanks, I can reproduce this - we'll take a look and fix asap

**Comment by seanlandsman** [comment]
Fixed - will be in the next release
