### ISSUE TITLE
How to pass down event handlers in cellRendererParams

### ISSUE THREAD

**Issue by kelsonic** [ceolter/ag-grid-react#49]
I'm not sure if this isn't supported or if I just haven't figured this out yet.

```
const columnDefs = [
  {
    headerName: 'Actions',
    width: 100,
    cellRenderer: reactCellRendererFactory(myComponent),
    cellRendererParams: {
      onClick: (rowData) => this.doSomethingWith(rowData),
      text: 'this is example text',
    },
  }, ...
```

`myComponent` does not respond to clicking despite assigning `onClick` in `cellRendererParams`, though it does have access to `this.props.text`.

What is the best way to do this? Also, `rowData` appears to be `undefined`, so what is the best way to get the data from the row that is selected in this case?

Thanks! :)

**Comment by kelsonic** [comment]
Oops, I apologize. I was not using `this.props.onClick` properly within `myComponent`.

**Comment by ceolter** [comment]
cellRendererParams get passed to the cellRenderer. so if you are providing your own cell renderer, these parameters will be passed to it, so if you are passing a function for onClick, then the cell renderer needs to do something with this function. if you don't do something with this in your myComponent, then nothing happens.
