### ISSUE TITLE
Registered Row Height callback (for getRowHeight) isn't invoked

### ISSUE THREAD

**Issue by srikantap** [ceolter/ag-grid-react#5]
getRowHeight callback (set using either props or setting it in gridOptions) isn't fired when the table is rendered. While setting the value (using rowHeight parameter in gridOptions) works, the callback seems to be stripped. 

This, assuming our understanding is right, is because "getRowHeight" doesn't have a match in Ag-Grid component's[ function name check](https://github.com/ceolter/ag-grid/blob/master/dist/ag-grid.js#L1135). Adding getRowHeight into the array fixes the issue.

**Comment by ceolter** [comment]
correct on your observation. i've just fixed this. will be fixed in next release.
