### ISSUE TITLE
cellEditingStopped / cellValueChanged causes grid to lose focus

### ISSUE THREAD

**Issue by cjtafoya** [ceolter/ag-grid-react#50]
Ag-grid loses focus after pressing 'tab' when attaching a function to cellEditingStopped and/or cellValueChanged. Using 7.1x on ag-grid-react / ag-grid.

**Comment by jo75** [comment]
same problem with ag-grid-ng2

**Comment by twogood** [comment]
+1

**Comment by seanlandsman** [comment]
Hi

@cjtafoya @jo75 @twogood - I've just tried this as follows:

    onCellEditingStopped={this.onCellEditingStopped.bind(this)}

And the tabbing seems to work as expected. Can you provide a simple plunker or similar (react or angular) that reproduces this problem?

**Comment by twogood** [comment]
Thanks @seanlandsman for your attention. My issue was not with cellEditingStopped or cellValueChanged but that my `newValueHandler` did `params.api.refreshRows([params.node]);` to update calculated values in other columns on the same row, and that caused loss of focus.

My workaround is to to implement  `onCellFocused`:
```
onCellFocused: function (params) {
          lastFocus = {
            rowIndex: params.rowIndex,
            colKey: params.column.colId
          };
        },
```
and restore focus by calling `params.api.setFocusedCell(lastFocus.rowIndex, lastFocus.colKey);` after  refreshRows

**Comment by seanlandsman** [comment]
@twogood ok, I understand - unfortunately as you say refreshing rows will indeed cause focus to be lost. Your solution is a good one.

thanks for following up

**Comment by cjtafoya** [comment]
Sorry I had lost track of this discussion; I came up with the same solution as @twogood ultimately.
