### ISSUE TITLE
React components not rendering properly through Cell Editor

### ISSUE THREAD

**Issue by YPBS** [ceolter/ag-grid-react#52]
I am using ag-grid and need editable dropdowns. As richSelect does not support editable feature, I am using react-select in my project. Issue is, when user starts typing in react-select the component is always bound within container of ag-grid cell due to which its filtered options are not displayed. 

Please find link to screenshot: http://imgur.com/XLanEE3 ,  I basically modified standard example of a-grid-react and inserted custom cell editor with react-select with 6 values. I tried setting z-index, height on select component. 

Is there any property/style in ag-grid does that may prevent elements inside it from ever going beyond cell's limits ?

**Comment by Developer-Y** [comment]
Same issue present with another popular React library react-autocomplete. This is causing serious issues in the project as ag-grid-react doesn't seems to be conflicting with other React libraries.

PFA screenshot http://imgur.com/nJtxU7e

**Comment by YPBS** [comment]
Same issue present with another popular React library react-autocomplete. This is causing serious issues in the project as ag-grid-react doesn't seems to be conflicting with other React libraries.

PFA screenshot http://imgur.com/nJtxU7e

**Comment by GaelGRIFFON** [comment]
Try with 
`    isPopup() {
        return true;
    }
`
inside the cell editor component.

I get the idea from here:
https://www.ag-grid.com/javascript-grid-cell-editor/?framework=react#gsc.tab=0
