### ISSUE TITLE
No Event triggered after data changed.

### ISSUE THREAD

**Issue by crapthings** [ceolter/ag-grid-react#53]
this work like componentDidMount

```
onGridReady={sizeColumnsToFit}
```

i can see updated value on cell when data was updated, but event not fired.

i have tried these...

```
rowDataChanged={sizeColumnsToFit}
cellValueChanged={sizeColumnsToFit}
modelUpdated={sizeColumnsToFit}
rowValueChanged={sizeColumnsToFit}
```

does stateless support those events?

**Comment by seanlandsman** [comment]
All events should be prefixed with "on", with the first letter of the event uppercase

For example, the event gridReady would be registered as onGridReady (as you already have)

For rowDataChanged, change it to onRowDataChanged={sizeColumnsToFit} - the same for the rest of the events
