### ISSUE TITLE
groupRowInnerRenderer isn't called

### ISSUE THREAD

**Issue by cistov** [ceolter/ag-grid-react#55]
I'm porting an existing application using ag-grid from Angular to React. It looks like `groupRowInnerRenderer` isn't called when using `ag-grid-react` wrapper. The same config works in Angular version. Any suggestions?

Simplified code:

```
this.options = {
  groupRowInnerRenderer: /* ... */ }, // not called
  columnDefs:  [
    { headerName: "Name", field: "name" },
    { headerName: "Report Name", field: "reportType", rowGroupIndex: 0, hide: true }
  ],
  rowData: [ /* ... */ ]
};

<AgGridReact gridOptions={this.options} />
```

* **ag-grid-react version:** 3.3
* **ag-Grid version:** 3.3
* **React version:** 15.4.2
* **Browser:** Chrome 50
* **Language:** ES6

**Comment by seanlandsman** [comment]
Hi

For the groupRowInnerRenderer - are you providing a React component here, or just a normal JavaScript function?

**Comment by cistov** [comment]
@seanlandsman just a plain function. `groupRowInnerRenderer` callback doesn't appear to get called here, while `onModelUpdated` is working fine on the other hand.

**Comment by seanlandsman** [comment]
I've just added an example to the https://github.com/ceolter/ag-grid-react-example repo (src-grouped) which demonstrates using a groupRowInnerRenderer

Please take a look and see if you can see how your app is different. I'm going to close this issue, but if after taking a look you believe that theres still an issue let me know and I can re-open

**Comment by cistov** [comment]
Thanks, I've found what the issue was by looking at your example - `groupUseEntireRow` wasn't set in my React version. It's all working now.

**Comment by seanlandsman** [comment]
@cistov good stuff!
