### ISSUE TITLE
Typescript Error: Cannot find module './lib/reactDateComponentFactory'

### ISSUE THREAD

**Issue by TrippBlunschi** [ceolter/ag-grid-react#56]
In 8.0.0, there is a typescript error in node_modules/ag-grid-react/main.d.ts. Cannot find module './lib/reactDateComponentFactory'

./lib/reactDateComponentFactory does not exist. Commenting out the export in main.d.ts seems to resolve the issue.

**Comment by andersrydman** [comment]
Experiencing the same issue. Fresh updated today.

**Comment by seanlandsman** [comment]
hi - we'll take a look at this today - thanks for reporting it, sorry for the hassle

**Comment by makinggoodsoftware** [comment]
This export will be removed in 8.0.1
