### ISSUE TITLE
Can we add "typings" attribute to npm package.json

### ISSUE THREAD

**Issue by j-sheppard** [ceolter/ag-grid-react#6]
In order to make it easy for Typescript to find the d.ts definition when packaged with node can we add the following attribute to the package.json in the npm package:
` "typings": "./main.d.ts"`
as per https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages 
(alternately rename `main.d.ts` to `index.d.ts`)

**Symptom**
When using NPM and installing ag-grid-react
`import {AgGridReact} from "ag-grid-react";`
gives
`error TS2307: Cannot find module 'ag-grid-react'.`

**Solution**
After adding the change above to package.json in the node_modules/ag-grid-react - the error disappears.

**Comment by ceolter** [comment]
fixed. i've also released the ag-grid-react project, so should work straight away.

**Comment by mellis481** [comment]
@ceolter How do I install the typings?  They are not appearing when I install `ag-grid-react` and there is no `@types/ag-grid-react` package.
