### ISSUE TITLE
A grid containing pinned and unpinned columns provides a lagging user experience when scrolling, in IE11

### ISSUE THREAD

**Issue by davidr-aggrid** [ceolter/ag-grid-react#61]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using a grid with pinned columns, vertical scrolling creates a laggy user experience in Internet Explorer 11. The pinned and unpinned grid content do not scroll together simultaneously. One side goes up or down as the user moves the scroll bar, but the other side does not move with it. Note that this behavior is NOT observed on Chrome. 

We set the property suppressScrollLag, but the laggy user experience persisted.

**Expected behavior**

The scrolling on Internet Explorer 11 would be as smooth as it is on Chrome.

**Minimal reproduction of the problem with instructions**

Easily reproduced: Run Internet Explorer 11 on a native box (not a virtual machine). Go to the grid with pinned and unpinned columns that is displayed on https://www.ag-grid.com/javascript-grid-pinning/#gsc.tab=0. Slowly scroll the grid vertically, observe the laggy behavior.

**What is the motivation / use case for changing the behavior?**

Sub-optimal user experience for Internet Explorer users.

**Please tell us about your environment:**

* **ag-grid-react version:** 2.0.X

Using ag-grid 7.0.2 and ag-grid-react 7.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

* **React version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Reproducible in Internet Explorer 11. Not observed in other browsers.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Hi

I'm afraid that this is the case with IE11 - we've worked as hard as we can to improve the performance with IE11 but its not at the stage where it's as soon as it's going to get.

You can try use the suppressScrollLag property which is really specifically for IE11 - it'll improve the overall user experience on an IE11 platform
