### ISSUE TITLE
Grid scrolls to top when rowData updated

### ISSUE THREAD

**Issue by dominykas** [ceolter/ag-grid-react#64]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When we provide a new object via `rowData` property, the grid scrolls to the top.

The issue seems to have been introduced in v8.2.x - https://github.com/ceolter/ag-grid/blob/25463a13d7eb84b358bbcf972997cd1dbe3ce7ec/dist/lib/rendering/rowRenderer.js#L175. The changelog seems to imply that this should only be used when paging through the grid:

> Enhancement: Pagination now scrolls to top when you load new page.

However, it seems that the scrolling happens when _any_ `newData` is introduced? We are using default `rowModelType` and default `pagination` (i.e. `false`).

**Expected behavior**

The grid should stay scrolled at the same position.

**Minimal reproduction of the problem with instructions**

1. Have some rows in the grid
2. Scroll down
3. Update `rowData`

**What is the motivation / use case for changing the behavior?**

We use the grid to provide real time updates - this means that the grid data updates rather frequently. We also only load partial data for some rows and request the remainder of the data for these rows only when they scroll into view (via `onViewportChanged` event) - when the full data loads up, this is also an update to `rowData`, which means the grid is scrolling back to the top.

**Please tell us about your environment:**

* **ag-grid-react version:** 9.0.0
* **ag-Grid/ag-Grid-Enterprise version:** 9.0.2
* **React version:** 15.5.3

* **Browser:** Latest Chrome (likely others)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by ceolter** [comment]
just implemented a new property: suppressScrollOnNewData

when true, the scroll to top will not happen.

will be in our next release.

**Comment by dominykas** [comment]
Thanks

**Comment by venkiramu** [comment]
> 
> 
> just implemented a new property: suppressScrollOnNewData
> 
> when true, the scroll to top will not happen.
> 
> will be in our next release.

Hi,
We are using ag-grid-enterprise v19.0.0 version. And we have tried property: suppressScrollOnNewData. But still not working. Is implementation available in above version ?

**Comment by cooljith91112** [comment]
@ceolter I'm having the same issue?
**ag-grid-enterprise v20.2.0**

**Comment by davidnoguerol** [comment]
I'm using `suppressScrollOnNewData: true` and it still scrolls to the top when `rowData` is changed. 

Version used (package.json):
`
{
...
    "ag-grid-community": "^20.2.0",
    "ag-grid-enterprise": "^20.2.0",
    "ag-grid-vue": "^20.2.0",
...
`
