### ISSUE TITLE
reactCellRendererFactory should accept additional props.

### ISSUE THREAD

**Issue by andrewtpoe** [ceolter/ag-grid-react#7]
Hello. Thank you for making the wonderful ag-grid and ag-grid-react libraries. They have been enormously helpful for me.

I have a suggestion that I believe would enhance the usability of this library. I am using functional programming to develop a react/redux application and require the ability to pass additional props in to the react cell render factory function. I am building cell renderers that convert to editable forms, and need to trigger actions in my container via `onChange` or `onClick` in the cells. These actions must be passed in as props.

I have modified the renderer so that it allows me to do this using ES6. I am unfamiliar with TypeScript and it will require research on my part before I can submit a proper pull request, however, I will post my solution here in case this will help someone else. Feel free to transpose this over to TypeScript if you are familiar with the library and no pull request has been submitted yet.

```JavaScript
import React from 'react';
import ReactDOM from 'react-dom';

const cellRenderer = (reactComponent, { ...props }) => (params) => {
  params.eParentOfValue.addElementAttachedListener((eCell) => {
    ReactDOM.render(React.createElement(reactComponent, { ...props, params }), eCell);
    params.api.addVirtualRowListener('virtualRowRemoved', params.rowIndex, () => {
      ReactDOM.unmountComponentAtNode(eCell);
    });
  });
  return null;
};

export default cellRenderer;
```

Using this as a cell renderer allows me pass in additional props in the following fashion while building my column definitions: 
```JavaScript
cellRenderer: cellRenderer(someCellRenderer, {
  testAction: this.testAction,
}),
```

The props in `someCellRenderer` is now: 
```JavaScript
console.log(this.props);
{
  testAction: function();
  params: Object;
}
```

Thank you again for your wonderful libraries.

**Comment by ceolter** [comment]
sorry for taking so long, very busy these last few days. and thanks for the PR.

i believe what you are trying to do is achievable through the grids context
http://localhost/angular-grid-context/index.php

in short, you put the extra properties that you want into the grids context (or if nothing else is in the context, just set the context to your extra props, the grid doesn't use the context, it's missing by default, you set it to what you want, and the grid passes the context to pretty much all the callbacks).

then in your renderer:
```
cellRenderer = function(params) {
   var extraProps = params.context; // or params.context.extraProps if you put other stuff in the context
}
```

**Comment by ceolter** [comment]
please advise. if i missed something, then please explain. if i haven't missed something, then we can close the issue.

**Comment by andrewtpoe** [comment]
It appears this may be possible to do with the context features you describe. I believe passing in props is a much cleaner interface and much more in line with React's development style. React documents state to use context sparingly, if at all (https://facebook.github.io/react/docs/context.html). I use context extremely infrequently in my work.

**Comment by ceolter** [comment]
i think you misunderstand!! the context i talk about is ag-Grid context, not the React context, it just happens that we both have the same name for similar concepts.

the ag-Grid context has nothing to do with the React context. it's a way for you to give the grid a bag of items that it then provides to all your cellRenderers etc. so when facebook say to not use the context, they are not talking bout ag-Grids!!

**Comment by dhassouni** [comment]
Isn't what @andrewtpoe is asking for available in the  cellRendererParams  property of the column definitions?  For instance, I was able to get additional props for my React component through in the manner below. Then, myCustomParam1 was accessible to me in MyReactTableCellRenderer as this.props.params.myCustomParam1.
```
colDefs.map((x) => {
    if (x.hasOwnProperty('unit')) {
        x.cellRenderer = reactCellRendererFactory(MyReactTableCellRenderer);
        x.cellRendererParams = {myCustomParam1: x.p1, myCustomParam2: x.p2};
    }
});
```

**Comment by ceolter** [comment]
yes i believe so. thanks for sharing.
