### ISSUE TITLE
How to make ag-grid-react Checkbox headerComponentFramework and cellRendererFramework communications?

### ISSUE THREAD

**Issue by shambhusingh** [ceolter/ag-grid-react#74]
Is there a way to stabilise communications between checkbox headerComponentFramework and cellRendererFramework, I am using react component for both the frameworks, wherein my app I am using redux as well but these both components are not directly connected with redux store, Here the issue is whenever I am checking or unchecking the header checkbox through api.selectAll and api.deselectAll respectively, either the both of components are not receiving any update by this action. Correct me if I am wrong, As per my knowledge any props update from the parent or container component will reach to the child or presentational components, which is not happening here. And I don't want to connect my checkbox components to the redux store.

So, Is there any solution for making the communication happen through the react-redux way? I know there are a lot ag-grid apis available for giving an alternate solution for this by using refresh view, cell or row or other way.

Here is my columnDefs for this.

columnDefs = [
  {
    width: 60,
    pinned: 'left',
    headerName: '',
    field: 'checkbox',
    cellRendererFramework: CellCheckbox,
    headerComponentFramework: HeaderCheckbox
  }
  ...
  ...
]

**Comment by seanlandsman** [comment]
As per the issue template please dont post support queries here. Use either stackoverflow or our Member Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5
