### ISSUE TITLE
AgGrid doesn't refresh when some features change

### ISSUE THREAD

**Issue by IceOnFire** [ceolter/ag-grid-react#77]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Besides #72 the grid actually refreshes when column definitions change, and even when the selection feature is enabled/disabled. However I can't make changes in pagination, filter, or sorting to refresh the grid.

**Expected behavior**
When `<AgGrid />` receives a new value for pagination, enableSorting/enableServerSideSorting, or enableFilter/enableServerSideFilter, it should refresh with the updated features.

**Minimal reproduction of the problem with instructions**
I'm creating a component such as this (omitting a *lot* of details):

```js
const MyComp = ({columns, rows, pagination, sorting, filter, rowSelection}) => (
  <AgGridReact
    columnDefs={columns}
    rows={rows}
    pagination={pagination}
    enableSorting={sorting}
    enableServerSideSorting={sorting}
    enableFilter={filter}
    enableServerSideFilter={filter}
    rowSelection={rowSelection}
  />
)
```

**What is the motivation / use case for changing the behavior?**
A powerful feature for the grid is to be customizable at runtime. It seems to be already, but not completely apparently.

**Please tell us about your environment:**

* **ag-grid-react version:** 11.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 11.0.0

* **React version:** 11.0.0

* **Browser:** all

* **Language:** ES6/JSX

**Comment by seanlandsman** [comment]
Hi

Most grid properties are initialisation time properties - ie they're read once and not again.

The properties you specify are some of these read-once properties - changing these values will not update the grid and this is by design.

If you wish to change this on the fly you'll need to destroy the grid and re-create it with the new property values

**Comment by IceOnFire** [comment]
Hi Sean,

I'm ok with destorying and recreating the grid in pure JS mode, but how can I achieve this with the React component? Shouldn't the component itself decide internally when to re-create itself or whether to perform incremental changes, letting the user just care of the render() method?

Antony

**Comment by seanlandsman** [comment]
Hi Antony,

The react component is really just a fairly thing wrapper over the core grid, with some additional features (such as supporting react components within the grid).

As the core grid doesn't support this (destroying & recreating the grid) it's not likely that we'll add support for this in the frameworks, primarily as it's not a common requirement - most people set these once and not again.

With regards to how this might be done in react, I guess the "parent" component that hosts the grid could control this - when one of these properties was to change the parent could hide/destroy the grid and recreate it. I've not tried this, but I can't see why this shouldn't work

I understand your use case, but as I say this is unlikely to change in the medium term I'm afraid

thanks

**Comment by brettinternet** [comment]
You could also use the `key` attribute in React's JSX. Then, the component will _remount_ each time that key's value changes.

```jsx
<div className="ag-theme-balham" key={`${settings.pagination}`}>
  <AgGridReact
    pagination={settings.pagination}
  />
</div>
```

For more information, see here: https://stackoverflow.com/questions/35792275/how-to-force-remounting-on-react-components

**Comment by SamOllason** [comment]
I have come across this behaviour when trying to give users the power to make grids 'editable' and 'non-editable'. I had to find a way to make sure that a user could toggle between these two options while still 'preserving' the customised layout of the grid (e.g. row grouping/column grouping etc.). This meant that unmounting and then remounting the component wasn't an option, as this appeared to users that the grid was 'reset' and removed their customisations.

A solution I found to get around the 'set at initialisation' feature of grid properties was to set the property to a function. This way you still define the property at initialisation time but you can control the value of the property dynamically. There is snippet below to demonstrate this, it may help you:

`
 <AgGridReact
       defaultColDef={{
            editable: () => {return this.props.editingInGridEnabled; },
       }}

        ...

/>
`
