### ISSUE TITLE
Use of React.DOM.div deprecated

### ISSUE THREAD

**Issue by TheTFo** [ceolter/ag-grid-react#78]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Warning:
C:\Dev\my-app\node_modules\react\lib\lowPriorityWarning.js:40 Warning: Accessing factories like React.DOM.div has been deprecated and will be removed in v16.0+. Use the react-dom-factories package instead.  Version 1.0 provides a drop-in replacement. For more info, see https://fb.me/react-dom-factories

**Expected behavior**

No warning
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

    AgGridReact.prototype.render = function () {
        var _this = this;
        return React.DOM.div({
            style: this.createStyleForDiv(),
            ref: function (e) {
                _this.eGridDiv = e;
            }
        });
    };

That will be deprecated.

**Please tell us about your environment:**

* **ag-grid-react version:** 11.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 11.0.0

* **React version:** 15.5

* **Browser:** Chrome

* **Language:** ES6

**Comment by seanlandsman** [comment]
Hi,

Thanks for this - I've raised issue AG-604 our side to track this. We'll update this thread with updates as soon as we have any

thanks

**Comment by seanlandsman** [comment]
Hi - this has been done and will be available in our next release

All warnings around 15.x have been dealt with to pave the way for 16.x, when it is finally released 

thanks

**Comment by llamasoft-dotcom-demo** [comment]
Thanks Sean!
