### ISSUE TITLE
React functional component and cell renderer framework exception

### ISSUE THREAD

**Issue by VyvIT** [ceolter/ag-grid-react#79]
**I'm submitting a bug**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```
**Current behavior**
When for cellRendererFramework a react component is provided as pure function, this line fails:
`
    class ReactCellRenderer extends AgReactComponent implements ICellRendererComp {

        constructor() {
            super(reactComponent, parentComponent);
        }

        public refresh(params: any): void {
            const componentRef = this.getFrameworkComponentInstance();
            if (componentRef.refresh) { <<<------------------------------------HERE componentRef === null
                componentRef.refresh(params);
            } else {
                throw new MethodNotImplementedException();
            }
        }
    }
    return ReactCellRenderer;
}`
Is this because React pure function components do not have refs and is it true then, that we should use class based react components in this case?

**Expected behavior**
Pure components render cells correctly.

**Minimal reproduction of the problem with instructions**
Could try to make a reproduction if necessary. Happens after changing rowData.

**What is the motivation / use case for changing the behavior?**
React components can be written in two ways and because our component syntax is validated with eslint airbnb style guide, components which can be written as pure functions are marked as warnings.

**Please tell us about your environment:**
Win10
* **ag-grid-react version:** 11.0.x

* **React version:** 15.6.1

* **Browser:** [all]

* **Language:** [ES6/7]

**Comment by seanlandsman** [comment]
Hi,

That's correct - we use the ref internally to get access to the actual instance in the cell, and in order to do so we need the react components to be class based

thanks
