### ISSUE TITLE
Allow Api access through `ref`

### ISSUE THREAD

**Issue by vanthiyathevan** [ceolter/ag-grid-react#8]
It would be benificial to allow access to the Grid and column `api` functions using [`refs`](https://facebook.github.io/react/docs/more-about-refs.html) instead of `onGridReady`

**Comment by ceolter** [comment]
according to here https://facebook.github.io/react/docs/more-about-refs.html,
the ref gives you a reference to the underlying DOM element (in the grids
case, this would be the div), the the Javascript objects behind it (which
the api is). so the ref won't work.

On 2 March 2016 at 03:26, Mohan Kethees <notifications@github.com> wrote:

> It would be benificial to allow access to the Grid and column api
> functions using refs
> <https://facebook.github.io/react/docs/more-about-refs.html> instead of
> onGridReady
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/ag-grid-react/issues/8>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by zeroasterisk** [comment]
It should work - working for other utilities returning react objects:
https://github.com/vazco/uniforms/blob/955e62ececa3150700dd333f0a694bbbe1c4e43c/README.md#methods

**Comment by ceolter** [comment]
if someone provides a PR i can consider??? it's not very obvious (to my anyway) how to do it re the link above.

**Comment by seanlandsman** [comment]
You can achieve what you want by doing something like this:


    <AgGridReact
           ref={(agGridReact) => { this.api = agGridReact.api}}
