### ISSUE TITLE
Date Filter: In Range condition - both dates should be interchangeable 

### ISSUE THREAD

**Issue by Dmon1Unlimited** [ceolter/ag-grid-react#80]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using inRange condition of date filter, swapping (dateFrom and dateTo) dates around does not give the same filtering result

**Expected behavior**
InRange should only care about the range, not the order of the dates. Whether I put the earliest date first or last shouldn't matter

**Minimal reproduction of the problem with instructions**
Any AG-grid, take the example grid shown below:
https://www.ag-grid.com/javascript-grid-date-component/#gsc.tab=0
For date column, if you select in range condition, and enter 
23-08-2008 
25-08-2008
you will get filtered results. But if you swap the dates around e.g.:
25-08-2008 
23-08-2008
you will get no results when there should have been

If the current behavior is a bug or you can illustrate your feature request better with an example,
please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
-->

**What is the motivation / use case for changing the behavior?**
Stable use of date filter. The user will not always put the earliest date first and latest date last. Since this condition is about range, the grid shouldn't care about the date order

**Please tell us about your environment:**

* **ag-grid-react version:** 2.0.X

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

* **React version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

While I agree this might be a nice to have, I don't think this qualifies as a bug, I would say all the in range controls I've seen have a from and a to and are not interchangeable, so not sure if doing this would contradict the user expectations.

We might add some visual clue if you enter a from > to though so it is obvious that is invalid.

I am going to close this as improving the UI for the controls in ag-grid is an ongoing task and we don't see this as important enough to be tracked on its own
